using 'main.bicep'

// -----------------------------------------------------------------------------
// Parameter values. Secrets and keys are supplied via environment variables and
// files under secrets/ (git-ignored). Run ./deploy.sh which stages these for you.
// -----------------------------------------------------------------------------

param location = 'westeurope'
param namePrefix = 'redisfx'
param adminUsername = 'azureuser'
param vmSize = 'Standard_B2ts_v2'

// Admin SSH public key (staged from ~/.ssh/id_ed25519.pub by deploy.sh).
param adminPublicKey = loadTextContent('secrets/admin_key.pub')

// Your public IP/CIDR allowed to SSH into client & forensics VMs.
param adminSourceAddress = readEnvironmentVariable('ADMIN_SOURCE_ADDRESS')

// Redis ACL role passwords (generated by deploy.sh; alphanumeric).
param readerPassword = readEnvironmentVariable('REDIS_READER_PASS')
param writerPassword = readEnvironmentVariable('REDIS_WRITER_PASS')
param adminPassword = readEnvironmentVariable('REDIS_ADMIN_PASS')

// Dedicated pull keypair (generated by scripts/gen-pull-key.sh).
param pullPrivateKey = loadTextContent('secrets/pull_key')
param pullPublicKey = loadTextContent('secrets/pull_key.pub')
